Ajout de la page Sale, Sales, Login, et rectification Header et Home
obledaym/woolly-front pull request #1
Opened 2019-04-07 16:48 UTC by Cathaiste

C'est un peu long pour une PR je sais mais avec les galères du début j'ai un peu push comme un mauvais sacripant. Du coup ce que j'ai fait dedans :
- Ajout de la page Sales qui regroupe tous les ventes en cours (plutôt que dans le home précédemment)
- Désormais dans la page Home, on appelle seulement le composant Sales pour l'instant
- Ajout de la page Sale qui montre le détail d'une vente (actuellement celle-ci n'est pas connecté aux informations recueilli par l'API)
- Ajout d'un package Font Awesome 
- Ajout d'une page Login qui affiche "Espace de connexion" et un bouton "se connecter"
- Rectification du header 
  - lorsque l'on clique sur "Woolly" redirige désormais vers l'accueil
  - lorsqu'on clique sur son nom, affiche le sous menu

2019-04-08 06:38 UTC, cesar-richard requested changes
Ok a part quelques petits détails. Je laisse les autres review les tests fonctionnels parce que je n'ai fait qu'une passe rapide sur la qualité de code.

2019-04-08 06:38 UTC, cesar-richard commented on woolly/src/pages/Sale.jsx
> +        const isConnected = true;
Why ?

2019-04-08 06:38 UTC, cesar-richard commented on woolly/src/pages/Sale.jsx
> +const OBJECT = {
Je suis pas d'accord pour utiliser un mot clef en tant que nom de classe.
Utilise Sale (en l'occurence) plutot, c'est bien plus clair, et moins dangereux

2019-04-08 06:38 UTC, cesar-richard commented on woolly/src/pages/Sale.jsx
> +        let tempArray = Array(OBJECT.items.length)
Voila typiquement pourquoi il vaut mieux utiliser le nom de la classe : c'est pas clair

2019-04-09 18:51 UTC, Cathaiste commented on woolly/src/pages/Sale.jsx
> +        const isConnected = true;
Pour prévoir quand on fera le lien avec l'API (ce que je ne sais pas faire, j'ai pas regardé la BDD encore et de ce que j'en ai vu j'avais l'impression qu'il manquait des informations) donc en attendant je simule

2019-04-09 18:52 UTC, Cathaiste commented on woolly/src/pages/Sale.jsx
> +const OBJECT = {
Pour "OBJECT" ? C'est pas un nom de classe, c'est la constante qui simule mon objet récupéré depuis la BDD, c'est aussi pour simuler, mais je peux changer le nom oui en effet

2019-04-09 18:54 UTC, Cathaiste commented on woolly/src/pages/Sale.jsx
> +        let tempArray = Array(OBJECT.items.length)
Je pense comprendre ce que tu veux dire, j'vais regarder ça

2019-04-14 16:54 UTC, cesar-richard approved these changes

2019-04-30 08:37 UTC, merged