Account view is working fine
obledaym/woolly-front pull request #6
Opened 2019-07-11 21:24 UTC by abrasseu

![image](https://user-images.githubusercontent.com/34026822/61086359-f2c7a100-a432-11e9-8582-9a45c1818639.png)

2019-07-11 21:39 UTC, NastuzziSamy requested changes
@abrasseu pls pls pls pls pls

2019-07-11 21:39 UTC, NastuzziSamy commented on woolly/src/pages/Account.jsx
> +							.all({ include: 'sale,orderlines,orderlines__item,orderlines__orderlineitems' }));
Brass, hum hum :p

2019-07-11 21:39 UTC, NastuzziSamy commented on woolly/src/App.jsx
>  								<Route path="/ventes/:sale_id" exact component={SaleDetail} />
En vrai, tu peux pas être crédible en faisant "français/_id" :/ 
Je veux des routes en anglais broooo

2019-07-11 21:39 UTC, NastuzziSamy commented
Je critique mais lourd taf bro, tu fais plaiz <3

2019-07-11 21:41 UTC, abrasseu commented on woolly/src/pages/Account.jsx
> +							.all({ include: 'sale,orderlines,orderlines__item,orderlines__orderlineitems' }));
C'est quoi le pb ?

2019-07-11 21:42 UTC, abrasseu commented on woolly/src/App.jsx
>  								<Route path="/ventes/:sale_id" exact component={SaleDetail} />
Les routes en français c'est pour le front, ce que l'utilisateur va voir c'est pour ça que c'est en français. Tu penses vraiment que c'est plus crédible en anglais ? (si oui chaud ahah)

2019-07-12 14:06 UTC, NastuzziSamy commented on woolly/src/pages/Account.jsx
> +							.all({ include: 'sale,orderlines,orderlines__item,orderlines__orderlineitems' }));
Je chippote sur ton include dynamique mais il est clean :)

2019-07-12 14:07 UTC, merged